apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: whgk5eq73-nodejs 
  janus-idp.io/tekton: whgk5eq73-nodejs
  backstage.io/kubernetes-id: whgk5eq73-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: whgk5eq73-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  