apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whgk5eq73-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whgk5eq73-nodejs 
  name: whgk5eq73-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: whgk5eq73-nodejs 
